name: calamity
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: paulw <email@example.com>

environment:
  sdk: '>=2.18.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  build_web_compilers: any

dependencies:
  build_runner: ^2.2.1
  # test: any
